/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module expmob1(inputs, outputs);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  input [0:31] inputs;
  wire [0:31] inputs;
  output [0:31] outputs;
  wire [0:31] outputs;
  sky130_fd_sc_hd__xor2_2 _049_ (
    .A(inputs[16]),
    .B(inputs[0]),
    .X(outputs[16])
  );
  sky130_fd_sc_hd__xor2_2 _050_ (
    .A(inputs[24]),
    .B(inputs[8]),
    .X(_028_)
  );
  sky130_fd_sc_hd__xor2_2 _051_ (
    .A(outputs[16]),
    .B(_028_),
    .X(outputs[24])
  );
  sky130_fd_sc_hd__xor2_2 _052_ (
    .A(inputs[0]),
    .B(inputs[8]),
    .X(outputs[8])
  );
  sky130_fd_sc_hd__xnor2_2 _053_ (
    .A(inputs[20]),
    .B(inputs[4]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xor2_2 _054_ (
    .A(inputs[28]),
    .B(inputs[12]),
    .X(_030_)
  );
  sky130_fd_sc_hd__xnor2_2 _055_ (
    .A(outputs[16]),
    .B(_029_),
    .Y(outputs[20])
  );
  sky130_fd_sc_hd__xnor2_2 _056_ (
    .A(_028_),
    .B(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xnor2_2 _057_ (
    .A(outputs[20]),
    .B(_031_),
    .Y(outputs[28])
  );
  sky130_fd_sc_hd__xnor2_2 _058_ (
    .A(inputs[4]),
    .B(inputs[12]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__xnor2_2 _059_ (
    .A(outputs[8]),
    .B(_032_),
    .Y(outputs[12])
  );
  sky130_fd_sc_hd__xor2_2 _060_ (
    .A(inputs[0]),
    .B(inputs[4]),
    .X(outputs[4])
  );
  sky130_fd_sc_hd__xnor2_2 _061_ (
    .A(inputs[18]),
    .B(inputs[2]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__xnor2_2 _062_ (
    .A(inputs[26]),
    .B(inputs[10]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__xnor2_2 _063_ (
    .A(_033_),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__xor2_2 _064_ (
    .A(inputs[22]),
    .B(inputs[6]),
    .X(_036_)
  );
  sky130_fd_sc_hd__xor2_2 _065_ (
    .A(inputs[30]),
    .B(inputs[14]),
    .X(_037_)
  );
  sky130_fd_sc_hd__xnor2_2 _066_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xnor2_2 _067_ (
    .A(_035_),
    .B(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__xnor2_2 _068_ (
    .A(outputs[28]),
    .B(_039_),
    .Y(outputs[30])
  );
  sky130_fd_sc_hd__xnor2_2 _069_ (
    .A(outputs[24]),
    .B(_035_),
    .Y(outputs[26])
  );
  sky130_fd_sc_hd__xnor2_2 _070_ (
    .A(_033_),
    .B(_036_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__xor2_2 _071_ (
    .A(outputs[20]),
    .B(_040_),
    .X(outputs[22])
  );
  sky130_fd_sc_hd__xnor2_2 _072_ (
    .A(outputs[16]),
    .B(_033_),
    .Y(outputs[18])
  );
  sky130_fd_sc_hd__xnor2_2 _073_ (
    .A(inputs[2]),
    .B(inputs[10]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__xnor2_2 _074_ (
    .A(outputs[8]),
    .B(_041_),
    .Y(outputs[10])
  );
  sky130_fd_sc_hd__xor2_2 _075_ (
    .A(inputs[6]),
    .B(inputs[14]),
    .X(_042_)
  );
  sky130_fd_sc_hd__xnor2_2 _076_ (
    .A(_032_),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xor2_2 _077_ (
    .A(outputs[10]),
    .B(_043_),
    .X(outputs[14])
  );
  sky130_fd_sc_hd__xor2_2 _078_ (
    .A(inputs[2]),
    .B(inputs[6]),
    .X(_044_)
  );
  sky130_fd_sc_hd__xor2_2 _079_ (
    .A(outputs[4]),
    .B(_044_),
    .X(outputs[6])
  );
  sky130_fd_sc_hd__xor2_2 _080_ (
    .A(inputs[0]),
    .B(inputs[2]),
    .X(outputs[2])
  );
  sky130_fd_sc_hd__xor2_2 _081_ (
    .A(inputs[17]),
    .B(inputs[1]),
    .X(_045_)
  );
  sky130_fd_sc_hd__xor2_2 _082_ (
    .A(inputs[21]),
    .B(inputs[5]),
    .X(_046_)
  );
  sky130_fd_sc_hd__xnor2_2 _083_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xnor2_2 _084_ (
    .A(inputs[25]),
    .B(inputs[9]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__xor2_2 _085_ (
    .A(inputs[29]),
    .B(inputs[13]),
    .X(_000_)
  );
  sky130_fd_sc_hd__xnor2_2 _086_ (
    .A(_048_),
    .B(_000_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__xnor2_2 _087_ (
    .A(_047_),
    .B(_001_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xnor2_2 _088_ (
    .A(inputs[19]),
    .B(inputs[3]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__xnor2_2 _089_ (
    .A(inputs[27]),
    .B(inputs[11]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__xnor2_2 _090_ (
    .A(_003_),
    .B(_004_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__xor2_2 _091_ (
    .A(inputs[23]),
    .B(inputs[7]),
    .X(_006_)
  );
  sky130_fd_sc_hd__xnor2_2 _092_ (
    .A(inputs[31]),
    .B(inputs[15]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__xnor2_2 _093_ (
    .A(_006_),
    .B(_007_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_2 _094_ (
    .A(_005_),
    .B(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xnor2_2 _095_ (
    .A(_002_),
    .B(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__xnor2_2 _096_ (
    .A(outputs[30]),
    .B(_010_),
    .Y(outputs[31])
  );
  sky130_fd_sc_hd__xor2_2 _097_ (
    .A(outputs[28]),
    .B(_002_),
    .X(outputs[29])
  );
  sky130_fd_sc_hd__xnor2_2 _098_ (
    .A(_045_),
    .B(_048_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xor2_2 _099_ (
    .A(_005_),
    .B(_011_),
    .X(_012_)
  );
  sky130_fd_sc_hd__xnor2_2 _100_ (
    .A(outputs[26]),
    .B(_012_),
    .Y(outputs[27])
  );
  sky130_fd_sc_hd__xor2_2 _101_ (
    .A(outputs[24]),
    .B(_011_),
    .X(outputs[25])
  );
  sky130_fd_sc_hd__xnor2_2 _102_ (
    .A(outputs[20]),
    .B(_047_),
    .Y(outputs[21])
  );
  sky130_fd_sc_hd__xnor2_2 _103_ (
    .A(_003_),
    .B(_006_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__xnor2_2 _104_ (
    .A(_040_),
    .B(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_2 _105_ (
    .A(outputs[21]),
    .B(_014_),
    .Y(outputs[23])
  );
  sky130_fd_sc_hd__xor2_2 _106_ (
    .A(_045_),
    .B(_003_),
    .X(_015_)
  );
  sky130_fd_sc_hd__xnor2_2 _107_ (
    .A(outputs[18]),
    .B(_015_),
    .Y(outputs[19])
  );
  sky130_fd_sc_hd__xor2_2 _108_ (
    .A(outputs[16]),
    .B(_045_),
    .X(outputs[17])
  );
  sky130_fd_sc_hd__xor2_2 _109_ (
    .A(inputs[1]),
    .B(inputs[9]),
    .X(_016_)
  );
  sky130_fd_sc_hd__xor2_2 _110_ (
    .A(inputs[5]),
    .B(inputs[13]),
    .X(_017_)
  );
  sky130_fd_sc_hd__xnor2_2 _111_ (
    .A(_016_),
    .B(_017_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__xor2_2 _112_ (
    .A(inputs[3]),
    .B(inputs[11]),
    .X(_019_)
  );
  sky130_fd_sc_hd__xor2_2 _113_ (
    .A(inputs[7]),
    .B(inputs[15]),
    .X(_020_)
  );
  sky130_fd_sc_hd__xnor2_2 _114_ (
    .A(_019_),
    .B(_020_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__xnor2_2 _115_ (
    .A(_018_),
    .B(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xnor2_2 _116_ (
    .A(outputs[14]),
    .B(_022_),
    .Y(outputs[15])
  );
  sky130_fd_sc_hd__xnor2_2 _117_ (
    .A(outputs[12]),
    .B(_018_),
    .Y(outputs[13])
  );
  sky130_fd_sc_hd__xnor2_2 _118_ (
    .A(_016_),
    .B(_019_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xnor2_2 _119_ (
    .A(outputs[10]),
    .B(_023_),
    .Y(outputs[11])
  );
  sky130_fd_sc_hd__xor2_2 _120_ (
    .A(outputs[8]),
    .B(_016_),
    .X(outputs[9])
  );
  sky130_fd_sc_hd__xnor2_2 _121_ (
    .A(inputs[1]),
    .B(inputs[5]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__xnor2_2 _122_ (
    .A(outputs[4]),
    .B(_024_),
    .Y(outputs[5])
  );
  sky130_fd_sc_hd__xor2_2 _123_ (
    .A(inputs[3]),
    .B(inputs[7]),
    .X(_025_)
  );
  sky130_fd_sc_hd__xnor2_2 _124_ (
    .A(_044_),
    .B(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__xnor2_2 _125_ (
    .A(outputs[5]),
    .B(_026_),
    .Y(outputs[7])
  );
  sky130_fd_sc_hd__xnor2_2 _126_ (
    .A(inputs[1]),
    .B(inputs[3]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xnor2_2 _127_ (
    .A(outputs[2]),
    .B(_027_),
    .Y(outputs[3])
  );
  sky130_fd_sc_hd__xor2_2 _128_ (
    .A(inputs[0]),
    .B(inputs[1]),
    .X(outputs[1])
  );
  sky130_fd_sc_hd__buf_2 _129_ (
    .A(inputs[0]),
    .X(outputs[0])
  );
endmodule
